## Part - A

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\vishal\Downloads\customer_credit_risk_dataset (1).csv")
df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,CUST00001,43.0,Female,West,Graduate,Salaried,1255415.10,634260.48,Education,739.70,1,14,0.5891,2023-11-04,0
1,CUST00002,27.0,Male,West,Graduate,Salaried,687624.60,551876.85,Other,663.82,2,15,0.3797,2023-02-05,1
2,CUST00003,48.0,Male,North,Primary,Self-Employed,251133.14,467369.16,Business,832.91,1,18,0.4692,2021-08-29,0
3,CUST00004,50.0,Male,East,Secondary,Salaried,631901.67,492151.94,Business,640.53,1,10,0.3464,2023-03-22,0
4,CUST00005,18.0,Male,West,Graduate,Self-Employed,758722.36,603651.51,Home,743.45,2,8,0.1458,2024-09-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.0,Male,West,Graduate,Salaried,1378354.83,2043299.23,NaN,587.17,1,19,0.3594,2024-03-17,1
996,CUST00997,48.0,Male,North,Secondary,Self-Employed,1588342.31,677916.43,Home,733.35,1,12,0.2053,2024-05-22,0
997,CUST00998,NaN,Male,North,Graduate,NaN,726924.67,306084.12,Car,723.75,2,11,0.3009,2025-12-25,0
998,CUST00999,41.0,Male,North,Graduate,Salaried,891465.93,702418.52,Home,775.20,1,13,0.5314,2025-12-09,1
999,CUST01000,49.0,Male,West,Secondary,Salaried,597359.84,NaN,Car,746.75,1,14,0.6685,2026-08-03,1

In [5]:
import json
import pandas as pd

with open(r"C:\Users\vishal\Downloads\customer_metadata.json", "r") as file:
    data = json.load(file)

df = pd.DataFrame(data)

print("Customer Metadata:")
print(df)

Customer Metadata:
  customer_id       city account_type  annual_income  loan_amount
0   CUST00001  Ahmedabad      Savings         650000       250000
1   CUST00002      Surat      Current         820000       400000
2   CUST00003     Rajkot      Savings         480000       150000

In [6]:
df = pd.read_csv(r"C:\Users\vishal\Downloads\customer_credit_risk_dataset (1).csv")
df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,CUST00001,43.0,Female,West,Graduate,Salaried,1255415.10,634260.48,Education,739.70,1,14,0.5891,2023-11-04,0
1,CUST00002,27.0,Male,West,Graduate,Salaried,687624.60,551876.85,Other,663.82,2,15,0.3797,2023-02-05,1
2,CUST00003,48.0,Male,North,Primary,Self-Employed,251133.14,467369.16,Business,832.91,1,18,0.4692,2021-08-29,0
3,CUST00004,50.0,Male,East,Secondary,Salaried,631901.67,492151.94,Business,640.53,1,10,0.3464,2023-03-22,0
4,CUST00005,18.0,Male,West,Graduate,Self-Employed,758722.36,603651.51,Home,743.45,2,8,0.1458,2024-09-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.0,Male,West,Graduate,Salaried,1378354.83,2043299.23,NaN,587.17,1,19,0.3594,2024-03-17,1
996,CUST00997,48.0,Male,North,Secondary,Self-Employed,1588342.31,677916.43,Home,733.35,1,12,0.2053,2024-05-22,0
997,CUST00998,NaN,Male,North,Graduate,NaN,726924.67,306084.12,Car,723.75,2,11,0.3009,2025-12-25,0
998,CUST00999,41.0,Male,North,Graduate,Salaried,891465.93,702418.52,Home,775.20,1,13,0.5314,2025-12-09,1
999,CUST01000,49.0,Male,West,Secondary,Salaried,597359.84,NaN,Car,746.75,1,14,0.6685,2026-08-03,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1000 non-null   object
 1   age                950 non-null    float64
 2   gender             970 non-null    object
 3   region             970 non-null    object
 4   education_level    1000 non-null   object
 5   employment_type    940 non-null    object
 6   annual_income      920 non-null    float64
 7   loan_amount        940 non-null    float64
 8   loan_purpose       960 non-null    object
 9   credit_score       930 non-null    float64
 10  repayment_history  1000 non-null   int64
 11  transaction_count  1000 non-null   int64
 12  spending_ratio     950 non-null    float64
 13  join_date          1000 non-null   object
 14  default_flag       1000 non-null   int64
dtypes: float64(5), int64(3), object(7)
memory usage: 117.3+ KB

In [8]:
df.describe

<bound method NDFrame.describe of     customer_id   age  gender region education_level employment_type  \
0     CUST00001  43.0  Female   West        Graduate        Salaried
1     CUST00002  27.0    Male   West        Graduate        Salaried
2     CUST00003  48.0    Male  North         Primary   Self-Employed
3     CUST00004  50.0    Male   East       Secondary        Salaried
4     CUST00005  18.0    Male   West        Graduate   Self-Employed
..          ...   ...     ...    ...             ...             ...
995   CUST00996  43.0    Male   West        Graduate        Salaried
996   CUST00997  48.0    Male  North       Secondary   Self-Employed
997   CUST00998   NaN    Male  North        Graduate             NaN
998   CUST00999  41.0    Male  North        Graduate        Salaried
999   CUST01000  49.0    Male   West       Secondary        Salaried

     annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0       1255415.10    634260.48    Education        739.70                  1
1        687624.60    551876.85        Other        663.82                  2
2        251133.14    467369.16     Business        832.91                  1
3        631901.67    492151.94     Business        640.53                  1
4        758722.36    603651.51         Home        743.45                  2
..             ...          ...          ...           ...                ...
995     1378354.83   2043299.23          NaN        587.17                  1
996     1588342.31    677916.43         Home        733.35                  1
997      726924.67    306084.12          Car        723.75                  2
998      891465.93    702418.52         Home        775.20                  1
999      597359.84          NaN          Car        746.75                  1

     transaction_count  spending_ratio   join_date  default_flag
0                   14          0.5891  2023-11-04             0
1                   15          0.3797  2023-02-05             1
2                   18          0.4692  2021-08-29             0
3                   10          0.3464  2023-03-22             0
4                    8          0.1458  2024-09-20             1
..                 ...             ...         ...           ...
995                 19          0.3594  2024-03-17             1
996                 12          0.2053  2024-05-22             0
997                 11          0.3009  2025-12-25             0
998                 13          0.5314  2025-12-09             1
999                 14          0.6685  2026-08-03             1

[1000 rows x 15 columns]>

In [9]:
df.isnull().sum()

customer_id           0
age                  50
gender               30
region               30
education_level       0
employment_type      60
annual_income        80
loan_amount          60
loan_purpose         40
credit_score         70
repayment_history     0
transaction_count     0
spending_ratio       50
join_date             0
default_flag          0
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer


mean_imputer = SimpleImputer(strategy="mean")
df[['age','annual_income','credit_score']] = mean_imputer.fit_transform(
    df[['age','annual_income','credit_score']]
)

median_imputer = SimpleImputer(strategy="median")
df[['loan_amount']] = median_imputer.fit_transform(df[['loan_amount']])

In [11]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df[['employment_type','gender']] = cat_imputer.fit_transform(
    df[['employment_type','gender']]
)

In [12]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df[['employment_type','gender']] = cat_imputer.fit_transform(
    df[['employment_type','gender']]
)

In [13]:
df['income_missing_flag'] = df['annual_income'].isnull().astype(int)

missing_count = df['annual_income'].isnull().sum()

random_values = df['annual_income'].dropna().sample(missing_count, replace=True)

df.loc[df['annual_income'].isnull(), 'annual_income'] = random_values.values

In [14]:
missing_count

np.int64(0)

In [15]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=5)

df[['annual_income','loan_amount','credit_score']] = knn_imputer.fit_transform(
    df[['annual_income','loan_amount','credit_score']]
)

In [16]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

mice_imputer = IterativeImputer(random_state=42)

df[['annual_income','loan_amount','credit_score']] = mice_imputer.fit_transform(
    df[['annual_income','loan_amount','credit_score']]
)

In [20]:
num_cols = ['annual_income','loan_amount','credit_score']

In [21]:
from scipy import stats

z_scores = np.abs(stats.zscore(df[num_cols]))

df_z = df[(z_scores < 3).all(axis=1)]

print("Before:", df.shape)
print("After Z-score:", df_z.shape)

Before: (1000, 16)
After Z-score: (974, 16)

In [22]:
df_iqr = df.copy()

for col in num_cols:
    Q1 = df_iqr[col].quantile(0.25)
    Q3 = df_iqr[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_iqr = df_iqr[(df_iqr[col] >= lower) & (df_iqr[col] <= upper)]

print("After IQR:", df_iqr.shape)

After IQR: (866, 16)

In [23]:
df_pct = df.copy()

for col in num_cols:
    lower = df_pct[col].quantile(0.01)
    upper = df_pct[col].quantile(0.99)

    df_pct = df_pct[(df_pct[col] >= lower) & (df_pct[col] <= upper)]

print("After Percentile:", df_pct.shape)

After Percentile: (940, 16)

In [24]:
from scipy.stats.mstats import winsorize

df_win = df.copy()

for col in num_cols:
    df_win[col] = winsorize(df_win[col], limits=[0.05, 0.05])

print("After Winsorization:", df_win.shape)

After Winsorization: (1000, 16)

In [27]:
df['join_date'] = pd.to_datetime(df['join_date'])

df['year'] = df['join_date'].dt.year
df['month'] = df['join_date'].dt.month
df['day'] = df['join_date'].dt.day
df['weekday'] = df['join_date'].dt.weekday
df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,income_missing_flag,year,month,day,weekday
0,CUST00001,43.000000,Female,West,Graduate,Salaried,1255415.10,634260.480,Education,739.70,1,14,0.5891,2023-11-04,0,0,2023,11,4,5
1,CUST00002,27.000000,Male,West,Graduate,Salaried,687624.60,551876.850,Other,663.82,2,15,0.3797,2023-02-05,1,0,2023,2,5,6
2,CUST00003,48.000000,Male,North,Primary,Self-Employed,251133.14,467369.160,Business,832.91,1,18,0.4692,2021-08-29,0,0,2021,8,29,6
3,CUST00004,50.000000,Male,East,Secondary,Salaried,631901.67,492151.940,Business,640.53,1,10,0.3464,2023-03-22,0,0,2023,3,22,2
4,CUST00005,18.000000,Male,West,Graduate,Self-Employed,758722.36,603651.510,Home,743.45,2,8,0.1458,2024-09-20,1,0,2024,9,20,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,Male,West,Graduate,Salaried,1378354.83,2043299.230,NaN,587.17,1,19,0.3594,2024-03-17,1,0,2024,3,17,6
996,CUST00997,48.000000,Male,North,Secondary,Self-Employed,1588342.31,677916.430,Home,733.35,1,12,0.2053,2024-05-22,0,0,2024,5,22,2
997,CUST00998,38.731579,Male,North,Graduate,Salaried,726924.67,306084.120,Car,723.75,2,11,0.3009,2025-12-25,0,0,2025,12,25,3
998,CUST00999,41.000000,Male,North,Graduate,Salaried,891465.93,702418.520,Home,775.20,1,13,0.5314,2025-12-09,1,0,2025,12,9,1
999,CUST01000,49.000000,Male,West,Secondary,Salaried,597359.84,436077.085,Car,746.75,1,14,0.6685,2026-08-03,1,0,2026,8,3,0

In [26]:
df['year']

0      2023
1      2023
2      2021
3      2023
4      2024
       ...
995    2024
996    2024
997    2025
998    2025
999    2026
Name: year, Length: 1000, dtype: int32

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])
df["gender"]

0      0
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: gender, Length: 1000, dtype: int64

In [31]:
df['income_bin'] = pd.cut(df['annual_income'], bins=4, labels=False)
df['income_bin']

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: income_bin, Length: 1000, dtype: int64

In [32]:
df[['income_bin']].isnull().sum()

income_bin    0
dtype: int64

In [33]:
df['credit_flag'] = (df[['credit_score']] > 700).astype(int)

In [34]:
df['credit_flag']

0      1
1      0
2      1
3      0
4      1
      ..
995    0
996    1
997    1
998    1
999    1
Name: credit_flag, Length: 1000, dtype: int64

In [36]:
df['income_quantile_bin'] = pd.qcut(df['annual_income'], q=4, labels=False)
df['income_quantile_bin'].isnull().sum()

np.int64(0)

In [39]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)

df['transaction_clustered'] = kmeans.fit_predict(df[['transaction_count']])
df['transaction_clustered']

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(

0      2
1      2
2      1
3      0
4      0
      ..
995    1
996    2
997    2
998    2
999    2
Name: transaction_clustered, Length: 1000, dtype: int32

In [40]:
df['transaction_cluster'] = df['transaction_clustered']
df['transaction_clustered']

0      2
1      2
2      1
3      0
4      0
      ..
995    1
996    2
997    2
998    2
999    2
Name: transaction_clustered, Length: 1000, dtype: int32

In [41]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

df_std = df.copy()
df_std[num_cols] = std_scaler.fit_transform(df_std[num_cols])

df_std

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,income_missing_flag,year,month,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster
0,CUST00001,43.000000,0,West,Graduate,Salaried,0.533361,0.058042,Education,0.751361,...,0,2023,11,4,5,0,1,3,2,2
1,CUST00002,27.000000,1,West,Graduate,Salaried,-0.162232,-0.074417,Other,-0.196784,...,0,2023,2,5,6,0,0,1,2,2
2,CUST00003,48.000000,1,North,Primary,Self-Employed,-0.696972,-0.210292,Business,1.916050,...,0,2021,8,29,6,0,1,0,1,1
3,CUST00004,50.000000,1,East,Secondary,Salaried,-0.230497,-0.170446,Business,-0.487800,...,0,2023,3,22,2,0,0,1,0,0
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,-0.075131,0.008828,Home,0.798218,...,0,2024,9,20,4,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,0.683973,2.323552,NaN,-1.154550,...,0,2024,3,17,6,0,0,3,1,1
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,0.941226,0.128234,Home,0.672016,...,0,2024,5,22,2,0,1,3,2,2
997,CUST00998,38.731579,1,North,Graduate,Salaried,-0.114086,-0.469613,Car,0.552060,...,0,2025,12,25,3,0,1,2,2,2
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.087492,0.167630,Home,1.194945,...,0,2025,12,9,1,0,1,2,2,2
999,CUST01000,49.000000,1,West,Secondary,Salaried,-0.272814,-0.260605,Car,0.839453,...,0,2026,8,3,0,0,1,1,2,2

In [43]:
from sklearn.preprocessing import Normalizer

norm = Normalizer()

df_norm = df.copy()
df_norm[num_cols] = norm.fit_transform(df_norm[num_cols])

df_norm

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,income_missing_flag,year,month,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster
0,CUST00001,43.000000,0,West,Graduate,Salaried,0.892556,0.450937,Education,0.000526,...,0,2023,11,4,5,0,1,3,2,2
1,CUST00002,27.000000,1,West,Graduate,Salaried,0.779884,0.625923,Other,0.000753,...,0,2023,2,5,6,0,0,1,2,2
2,CUST00003,48.000000,1,North,Primary,Self-Employed,0.473329,0.880884,Business,0.001570,...,0,2021,8,29,6,0,1,0,1,1
3,CUST00004,50.000000,1,East,Secondary,Salaried,0.788945,0.614464,Business,0.000800,...,0,2023,3,22,2,0,0,1,0,0
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,0.782539,0.622601,Home,0.000767,...,0,2024,9,20,4,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,0.559230,0.829013,NaN,0.000238,...,0,2024,3,17,6,0,0,3,1,1
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,0.919731,0.392548,Home,0.000425,...,0,2024,5,22,2,0,1,3,2,2
997,CUST00998,38.731579,1,North,Graduate,Salaried,0.921630,0.388068,Car,0.000918,...,0,2025,12,25,3,0,1,2,2,2
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.785469,0.618900,Home,0.000683,...,0,2025,12,9,1,0,1,2,2,2
999,CUST01000,49.000000,1,West,Secondary,Salaried,0.807684,0.589615,Car,0.001010,...,0,2026,8,3,0,0,1,1,2,2

In [44]:

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df_minmax[num_cols])

df_minmax

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,income_missing_flag,year,month,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster
0,CUST00001,43.000000,0,West,Graduate,Salaried,0.079685,0.082934,Education,0.699625,...,0,2023,11,4,5,0,1,3,2,2
1,CUST00002,27.000000,1,West,Graduate,Salaried,0.040862,0.071006,Other,0.604775,...,0,2023,2,5,6,0,0,1,2,2
2,CUST00003,48.000000,1,North,Primary,Self-Employed,0.011017,0.058770,Business,0.816138,...,0,2021,8,29,6,0,1,0,1,1
3,CUST00004,50.000000,1,East,Secondary,Salaried,0.037052,0.062358,Business,0.575662,...,0,2023,3,22,2,0,0,1,0,0
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,0.045724,0.078502,Home,0.704313,...,0,2024,9,20,4,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,0.088091,0.286943,NaN,0.508962,...,0,2024,3,17,6,0,0,3,1,1
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,0.102448,0.089255,Home,0.691688,...,0,2024,5,22,2,0,1,3,2,2
997,CUST00998,38.731579,1,North,Graduate,Salaried,0.043549,0.035418,Car,0.679688,...,0,2025,12,25,3,0,1,2,2,2
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.054800,0.092802,Home,0.744000,...,0,2025,12,9,1,0,1,2,2,2
999,CUST01000,49.000000,1,West,Secondary,Salaried,0.034690,0.054239,Car,0.708438,...,0,2026,8,3,0,0,1,1,2,2

In [46]:
from sklearn.preprocessing import MaxAbsScaler

maxabs = MaxAbsScaler()

df_maxabs = df.copy()
df_maxabs[num_cols] = maxabs.fit_transform(df_maxabs[num_cols])

df_maxabs

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,income_missing_flag,year,month,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster
0,CUST00001,43.000000,0,West,Graduate,Salaried,0.085313,0.091022,Education,0.754796,...,0,2023,11,4,5,0,1,3,2,2
1,CUST00002,27.000000,1,West,Graduate,Salaried,0.046728,0.079199,Other,0.677367,...,0,2023,2,5,6,0,0,1,2,2
2,CUST00003,48.000000,1,North,Primary,Self-Employed,0.017066,0.067072,Business,0.849908,...,0,2021,8,29,6,0,1,0,1,1
3,CUST00004,50.000000,1,East,Secondary,Salaried,0.042942,0.070628,Business,0.653602,...,0,2023,3,22,2,0,0,1,0,0
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,0.051560,0.086630,Home,0.758622,...,0,2024,9,20,4,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,0.093668,0.293233,NaN,0.599153,...,0,2024,3,17,6,0,0,3,1,1
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,0.107938,0.097287,Home,0.748316,...,0,2024,5,22,2,0,1,3,2,2
997,CUST00998,38.731579,1,North,Graduate,Salaried,0.049399,0.043926,Car,0.738520,...,0,2025,12,25,3,0,1,2,2,2
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.060581,0.100804,Home,0.791020,...,0,2025,12,9,1,0,1,2,2,2
999,CUST01000,49.000000,1,West,Secondary,Salaried,0.040594,0.062581,Car,0.761990,...,0,2026,8,3,0,0,1,1,2,2

In [48]:
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()

df_robust = df.copy()
df_robust[num_cols] = robust.fit_transform(df_robust[num_cols])

df_robust

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,income_missing_flag,year,month,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster
0,CUST00001,43.000000,0,West,Graduate,Salaried,1.229088,0.504623,Education,0.672930,...,0,2023,11,4,5,0,1,3,2,2
1,CUST00002,27.000000,1,West,Graduate,Salaried,-0.065767,0.294855,Other,-0.176243,...,0,2023,2,5,6,0,0,1,2,2
2,CUST00003,48.000000,1,North,Primary,Self-Employed,-1.061193,0.079677,Business,1.716044,...,0,2021,8,29,6,0,1,0,1,1
3,CUST00004,50.000000,1,East,Secondary,Salaried,-0.192845,0.142780,Business,-0.436881,...,0,2023,3,22,2,0,0,1,0,0
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,0.096372,0.426685,Home,0.714897,...,0,2024,9,20,4,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,1.509454,4.092381,NaN,-1.034033,...,0,2024,3,17,6,0,0,3,1,1
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,1.988333,0.615782,Home,0.601868,...,0,2024,5,22,2,0,1,3,2,2
997,CUST00998,38.731579,1,North,Graduate,Salaried,0.023857,-0.330994,Car,0.494434,...,0,2025,12,25,3,0,1,2,2,2
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.399096,0.678170,Home,1.070211,...,0,2025,12,9,1,0,1,2,2,2
999,CUST01000,49.000000,1,West,Secondary,Salaried,-0.271618,0.000000,Car,0.751827,...,0,2026,8,3,0,0,1,1,2,2

In [50]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

log_transform = FunctionTransformer(np.log1p)
df['log_spending'] = log_transform.fit_transform(df[['spending_ratio']])

sqrt_transform = FunctionTransformer(np.sqrt)
df['sqrt_spending'] = sqrt_transform.fit_transform(df[['spending_ratio']])

df['reciprocal_spending'] = 1 / (df['spending_ratio'] + 1e-5)
df['reciprocal_spending']

0      1.697476
1      2.633589
2      2.131242
3      2.886753
4      6.858240
         ...
995    2.782338
996    4.870683
997    3.323253
998    1.881786
999    1.495864
Name: reciprocal_spending, Length: 1000, dtype: float64

In [51]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method='yeo-johnson')

df[['annual_income','loan_amount']] = pt.fit_transform(
    df[['annual_income','loan_amount']]
)

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_cols = ['annual_income','loan_amount']
cat_cols = ['gender']

ct = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(), cat_cols)
])

transformed_data = ct.fit_transform(df)
print("Transformed Data Shape:", transformed_data.shape)

Transformed Data Shape: (1000, 5)

In [54]:
df

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,...,day,weekday,income_bin,credit_flag,income_quantile_bin,transaction_clustered,transaction_cluster,log_spending,sqrt_spending,reciprocal_spending
0,CUST00001,43.000000,0,West,Graduate,Salaried,1.085720,0.511548,Education,739.70,...,4,5,0,1,3,2,2,0.463168,0.767529,1.697476
1,CUST00002,27.000000,1,West,Graduate,Salaried,0.026397,0.312860,Other,663.82,...,5,6,0,0,1,2,2,0.321866,0.616198,2.633589
2,CUST00003,48.000000,1,North,Primary,Self-Employed,-1.874548,0.070465,Business,832.91,...,29,6,0,1,0,1,1,0.384718,0.684982,2.131242
3,CUST00004,50.000000,1,East,Secondary,Salaried,-0.126792,0.146414,Business,640.53,...,22,2,0,0,1,0,0,0.297434,0.588558,2.886753
4,CUST00005,18.000000,1,West,Graduate,Self-Employed,0.203344,0.441350,Home,743.45,...,20,4,0,1,2,0,0,0.136103,0.381838,6.858240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST00996,43.000000,1,West,Graduate,Salaried,1.245224,2.039632,NaN,587.17,...,17,6,0,0,3,1,1,0.307043,0.599500,2.782338
996,CUST00997,48.000000,1,North,Secondary,Self-Employed,1.484864,0.605264,Home,733.35,...,22,2,0,1,3,2,2,0.186728,0.453100,4.870683
997,CUST00998,38.731579,1,North,Graduate,Salaried,0.126535,-0.572495,Car,723.75,...,25,3,0,1,2,2,2,0.263056,0.548544,3.323253
998,CUST00999,41.000000,1,North,Graduate,Salaried,0.490054,0.654901,Home,775.20,...,9,1,0,1,2,2,2,0.426182,0.728972,1.881786
999,CUST01000,49.000000,1,West,Secondary,Salaried,-0.229313,-0.032256,Car,746.75,...,3,0,0,1,1,2,2,0.511925,0.817618,1.495864